server:
  port: 10041
spring:
  datasource:
    url: jdbc:mysql://192.168.20.107:3306/rf_raven
    username: lifan
    password: 123456

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl