server:
  port: 10011

spring:
  redis:
    #无此属性或者为false则不开启redis
    enable: true
    host: 192.168.20.107
    database: 3
    port: 6379
    # password: 123456
    jedis:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 0